---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbclaim
  labels:
    env: dev
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile-premium