---
apiVersion: v1
kind: Pod
metadata:
  name: std-db
  labels:
    version: dev
    db: std-db
  namespace: dev
spec:
  volumes:
    - name: std-db-vol
      persistentVolumeClaim:
        claimName: dbclaim
  containers:
    - name: std-db
      image: mysql:5.7
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootroot
        - name: MYSQL_DATABASE
          value: std-db
        - name: MYSQL_USER
          value: less
        - name: MYSQL_PASSWORD
          value: lessvaas
      ports:
        - name: db-port
          containerPort: 3306
          protocol: TCP
      volumeMounts:
        - name: std-db-vol
          mountPath: /var/lib/mysql