apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
namespace: dev
namePrefix: dev-
labels:
  - pairs:
      env: dev
    includeTemplates: true
replicas:
- name: sra
  count: 4
images:
  - name: anasansarii/scra
    newName: anasansarii/scra
    newTag: dev-4

