apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
namespace: dev
namePrefix: dev
labels:
  - pairs:
      version: dev
    includeTemplates: true
replicas:
- name: sra
  count: 3
images:
  - name: anasansarii/scra
    newName: anasansarii/scra

