---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sra
  labels:
    version: dev
    app: sra
  namespace: dev
spec:
  minReadySeconds: 2
  replicas: 2
  selector:
    matchLabels:
      app: sra
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  template:
    metadata:
      name: sra
      labels:
        app: sra
        version: dev
      namespace: dev
    spec:
      containers:
        - name: sra
          image: anasansarii/scra:dev-4
          ports:
            - name: sraport
              containerPort: 8080
              protocol: TCP
          env:
            - name: MYSQL_SERVER
              value: internal-db-svc
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
            requests:
              memory: "64Mi"
              cpu: "150m"
