apiVersion: v1
kind: Service
metadata:
  name: sra-svc
  labels:
    version: dev
  namespace: dev
spec:
  type: LoadBalancer
  ports:
    - name: sra-port
      targetPort: 8080
      port: 80
  selector:
    app: sra