apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
namespace: qa
namePrefix: qa-
labels:
  - pairs:
      env: qa
    includeTemplates: true
replicas:
- name: sra
  count: 3
images:
  - name: anasansarii/scra
    newName: anasansarii/scra
